# https://starship.rs/config/
# Disable the newline at the start of the prompt
add_newline = true
# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "line_break",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "golang",
    "haskell",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 60

[character]
symbol = "â¯â¯"
error_symbol = "âœ˜â¯"
use_symbol_for_status = true

[directory]
style = "cyan"
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "purple"

[git_commit]
style = "green"

[git_state]
style = "yellow"

[git_status]
style = "red"
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
deleted_count.enabled = true
# diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·â€"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged.value = "++"
# staged.style = "yellow"
staged_count.enabled = true
# staged_count.style = "green"
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"

[hostname]
ssh_only = false
# prefix = "âŸª"
# suffix = "âŸ«"
style = "blue"
disabled = false

[line_break]
disabled = false

[nodejs]
style = "yellow"

[package]
style = "cyan"

[python]
style = "yellow"

[username]
style_root = "bold red"
style_user = "blue"
show_always = true
disabled = false
